_target_: goalagent.env.rg_env.RgEnv

simulator:
  _target_: srccode.simulator.CasADi
  system:
    _target_: goalagent.env.lunar_lander.LunarLanderWithOffset
  state_init: = np.array([[-10.0, 45.0, 2 * np.pi / 3.0, 0.0, 0.0, 0.0]])

  # _target_: goalagent.env.utils.random_state_simulator.StateInitRandomSamplerSimulator
  # system: 
  #   _target_: goalagent.env.lunar_lander.LunarLander
  # state_init: 
  #   _target_: goalagent.env.utils.random_state_simulator.UniformStateInitGenerator
  #   bounds: 
  #     - = [10.0, 10.0]
  #     - = [35.0, 35.0]
  #     - = [2 * np.pi / 3.0 - 0.0, 2 * np.pi / 3.0 + 0.0]
  #     - = [0.0, 0.0]
  #     - = [0.0, 0.0]
  #     - = [0.0, 0.0]
  time_final: 20 
  max_step: 0.1
  
running_objective:
  _target_: goalagent.env.running_objective.LunarLanderRunningObjective
  weights: = numpy.array([100.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0])
  biases: = numpy.array([0., 1., 0., 0., 0., 0.])