observations_names:
  - cos_angle
  - sin_angle
  - angle_vel

actions_names:
  - torque

# nominal_policy:
#   _target_: goalagent.env.pendulum.PendulumStabilizingPolicy
#   gain: 0.6
#   action_min: -2
#   action_max: 2
#   switch_loc: = numpy.cos(numpy.pi / 10)
#   switch_vel_loc: 0.2
#   pd_coeffs: = [12, 4]
#   system: 
#     _target_: goalagent.env.pendulum.InvertedPendulum

observer:
  _target_: goalagent.env.pendulum.PendulumObserver

origin: = torch.tensor([1., 0., 0.])

checkpoint_path: pendulum-v1