_target_: goalagent.env.rg_env.RgEnv

simulator:
  _target_: srccode.simulator.CasADi
  system: 
    _target_: goalagent.env.two_tank.TwoTankWithOffset
  state_init: = numpy.array([[2., -2.]])
  time_final: 80
  max_step: 0.1
running_objective:
  _target_: goalagent.env.running_objective.QuadraticRunningObjective
  weights: = numpy.array([10., 10., 0.])
  biases: = numpy.array([0.4, 0.4])
