_target_: goalagent.env.rg_env.RgEnv

simulator:
  _target_: goalagent.env.utils.random_state_simulator.StateInitRandomSamplerSimulator
  system: 
    _target_: goalagent.env.pendulum.PendulumQuanser
  state_init: 
    _target_: goalagent.env.utils.random_state_simulator.UniformStateInitGenerator
    bounds: 
      - = [numpy.pi - numpy.pi / 100, numpy.pi + numpy.pi / 100]
      - = [-1, 1]
    
  time_final: 10
  max_step: $ env_spec.sampling_time
running_objective: $ env_spec.running_objective