observations_names:
  - cos_angle
  - sin_angle
  - angle_vel

actions_names:
  - torque

eval_env:
  _target_: goalagent.env.rg_env.RgEnv

  simulator:
    _target_: srccode.simulator.CasADi
    system: 
      _target_: goalagent.env.pendulum.PendulumQuanserWithGymObservation
    state_init: = numpy.array([[numpy.pi, 1.]])
    time_final: 10
    max_step:  0.01
  running_objective:
    _target_: goalagent.env.running_objective.GymPendulumRunningObjective

eval_n_steps: 1002